version: "3"

services:
  diplom:
    container_name: index_downloader
    command: python3 scripts/index_downloader.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - index_downloader:/app/data

volumes:
  index_downloader: